
from reportlab.lib.pagesizes import *

from .workbook_generator import WorkbookGenerator, WorkbookMode
from .sentence_finder import SentenceFinder

PAGE_SIZES = {
    'A0': A0,
    'A1': A1,
    'A2': A2,
    'A3': A3,
    'A4': A4,
    'A5': A5,
    'A6': A6,
    'A7': A7,
    'A8': A8,
    'A9': A9,
    'A10': A10,
    'B0': B0,
    'B1': B1,
    'B2': B2,
    'B3': B3,
    'B4': B4,
    'B5': B5,
    'B6': B6,
    'B7': B7,
    'B8': B8,
    'B9': B9,
    'B10': B10,
    'C0': C0,
    'C1': C1,
    'C2': C2,
    'C3': C3,
    'C4': C4,
    'C5': C5,
    'C6': C6,
    'C7': C7,
    'C8': C8,
    'C9': C9,
    'C10': C10,
    'LETTER': LETTER,
    'LEGAL': LEGAL,
    'ELEVENSEVENTEEN': ELEVENSEVENTEEN,
    'JUNIOR_LEGAL': JUNIOR_LEGAL,
    'HALF_LETTER': HALF_LETTER,
    'GOV_LETTER': GOV_LETTER,
    'GOV_LEGAL': GOV_LEGAL,
    'TABLOID': TABLOID,
    'LEDGER': LEDGER
}